image: alpine/edge
oauth: pages.sr.ht/PAGES:RW
packages:
- hut
environment:
  site: rau.srht.site
secrets:
  - e7a0f0ec-1757-4b43-a14e-acfc4ca5dc5d
tasks:
- package: |
    cd web
    tar -cvz . > ../site.tar.gz
- upload: |
    hut pages publish -d $site site.tar.gz
- mirror: |
    cd web
    git remote add github git@github.com:aurob/web.git
    git push --mirror github