environment:
  site: rau.srht.site
  github_repo: git@github.com:aurob/web.git
  repo: web

image: alpine/edge

packages:
- hut
- git
- openssh-client

secrets:
- f19991f7-356b-4348-91bc-734d5f3ffffd

sources:
- "git@git.sr.ht:~rau/web"

tasks:
- package: |
    cd web
    tar -cvz . > ../site.tar.gz
    
- upload: |
    hut pages publish -d $site site.tar.gz
    
- push-to-github: |-
    cd "$repo"
    
    ssh-keyscan github.com >> ~/.ssh/known_hosts
    
    git remote add github "$github_repo" || git remote set-url github "$github_repo"
    
    git push github HEAD:main
    
oauth: pages.sr.ht/PAGES:RW
